### ISSUE TITLE
Change the way Maintenance Mode works

### ISSUE THREAD

**Issue by Drek282** [Drek282/PsychoStats#100]
Right now maintenance mode completely shuts down the stats front end and only allows access to the ACP.  It replaces the stats with a note indicating the stats  are in maintenance mode.  Please add your suggestions as to how you would like it to work.

I believe what has been suggested so far is that the stats should display for logged in admins, with a note to remind admins that the stats are in maintenance mode.  This would allow admins to tweak the stats and see the results before taking them out of maintenance mode.

**Comment by Rosenstein** [comment]
> 
> I believe what has been suggested so far is that the stats should display for logged in admins, with a note to remind admins that the stats are in maintenance mode.  This would allow admins to tweak the stats and see the results before taking them out of maintenance mode.

This, yes 🙂

**Comment by Drek282** [comment]
Complete.
