### ISSUE TITLE
Warning: Undefined array key "player_left_column_mod

### ISSUE THREAD

**Issue by kimsook** [Drek282/PsychoStats#108]
Hi there, really liking this version of Psychostats, well done!

I am however receiving the following error on the left and side panel. Please see image below. Just to note that I am running this off a dedicated linux server with nginx and using PHP v8.1.29.

Warning: Undefined array key "player_left_column_mod" in /var/www/psychostats/hl/www/temp/default-en_US-^%%8E^8E6^8E68F3EB%%player.html.php on line 321

![error](https://github.com/user-attachments/assets/eb6cf460-d90e-4f1e-ad1c-edc237f29daa)

**Comment by kimsook** [comment]
It seems I get this on most pages, here I am browsing the maps statistics page.

![error2](https://github.com/user-attachments/assets/1fcf5869-31c2-4bb7-8076-ca3abaeb4bec)

**Comment by kimsook** [comment]
Thanks Drek, I will wait further instruction 👍

**Comment by Drek282** [comment]
Can you tell me what mod you are running please, and a link to your stats might also be helpful.

**Comment by kimsook** [comment]
https://stats.hlds.uk/

I am running valve (half-life deathmatch)

**Comment by Drek282** [comment]
Ok, thank you, that isn't well tested.  I may require some logs from your server, but I will let you know.  If you want to send them to me anyway, a couple of days from days when your server is busy (even if it's just bots) would be helpful.  You can zip them up and email them to me at olstairs at rogers dot com, or put them up somewhere where I can download them and email me the link.

**Comment by kimsook** [comment]
Thanks, i've sent those on to you now.

**Comment by Drek282** [comment]
I believe this has been fixed.  The only action you need to take is to download www/includes/PS/halflife/hldm.php from the hldm module and upload it to your webfolder.  If you find any other problems, please don't hesitate to post a new issue.

**Comment by kimsook** [comment]
That is wonderful Drek, thank you very much. That is working perfectly now. That file was actually missing from install.

**Comment by Drek282** [comment]
I had to create it.  When PS was first coded you didn't need to declare every variable, array and key.  Now you do.  That was the issue.

**Comment by Drek282** [comment]
Adding another note here.  I have now tested PS on nginx, and everything appears to function normally, as it does on apache2.
