### ISSUE TITLE
Add a list of necessary PHP modules and Perl modules to the INSTALL.md, and/or the WIKI

### ISSUE THREAD

**Issue by Rosenstein** [Drek282/PsychoStats#21]
Tracking issue.

**Comment by Drek282** [comment]
I think this is best done in the wiki.

**Comment by janzagata** [comment]
I've created Docker setup that contains cpanfile (perl "package manager") to install dependencies. Should I push it to close this issue?

**Comment by Drek282** [comment]
Is it OS dependent, ie. does it work on Linux, Windows and Mac?

**Comment by Drek282** [comment]
If it doesn't work on all three we can't accept something like that.  We need to try to keep this OS independent.  Docker is a Linux thing I think.

**Comment by Drek282** [comment]
More importantly does it work without having to install anything else.  I'm not familiar with Docker.  A bit of googling didn't help me a lot.

**Comment by janzagata** [comment]
In theory, Docker should be last thing you have to install :)) Rest should be matter of one or two commands. AFAIK it should run at all platforms, but I cannot verify.

**Comment by Drek282** [comment]
Push it and I'll look at it.  Worst case scenario it doesn't get used, but thank you for the effort and contribution regardless.

**Comment by Drek282** [comment]
bcmath php module is required for steam urls and addiing friends in  the player profile.

**Comment by janzagata** [comment]
I've finally pushed the Docker setup. see https://github.com/Drek282/PsychoStats/pull/60
Think we can close this issue now?

**Comment by Drek282** [comment]
No, I still need to poke at it, but you can stop following it if you like.

**Comment by Drek282** [comment]
I am in the process of changing the class_valve library to xPaw's SteamID library.  When I finish that the php bcmath module will no longer be required but the php gmp module will be.

**Comment by Drek282** [comment]
Done.

**Comment by Drek282** [comment]
PHP Curl module is also now required.

**Comment by Drek282** [comment]
Added the CURL module to the install checklist.

**Comment by Drek282** [comment]
I think this is long done.
