### ISSUE TITLE
Uninstall plugins broken.

### ISSUE THREAD

**Issue by Drek282** [Drek282/PsychoStats#46]

**Comment by Drek282** [comment]
Not sure if this is truly broken or not.  I was able to successfully install and reinstall a plugin, but got a fatal error and had to reload the admin plugins page, which it did successfully.  I think this might have been related to the globals and PHP_SELF artifacts.

**Comment by angelperezleon** [comment]
got logs of the errors?
in past for me problem was with permissions.

**Comment by Drek282** [comment]
I will check the logs if I get this error again.  I've generally found the uninstall for plugins to be a bit flaky, but usually it just requires reloading to page to fix the error.  Hasn't been a big priority but I will try to do some testing and check the logs to see what is going on.
