### ISSUE TITLE
Headshots to BOTS should not be counted when BOT Ignore flag is set.

### ISSUE THREAD

**Issue by janzagata** [Drek282/PsychoStats#53]
In general statistics, headshots dealed to BOT players are counted in overall HS percentage even when BOT Ignore flag is set at settings. It creates situations, where player can have excessive HS percentage, or have more HS than kills.

I had no time to investigate this further, therefore im not sure if its bug in Psychostats or cstrikes plugin. 
![Screenshot_20210715_074228](https://user-images.githubusercontent.com/9821497/125734995-de56548b-67d7-4bd4-a7c4-643e33ecf341.png)

**Comment by Drek282** [comment]
Thank you for your report.  Can you tell me what game/mod this is?  I have a mod where there are headshots and I have bots excluded and I'm not seeing that.  So there's a good chance it has to do with a specific mod.  If you can attach about a day's worth of server logs that would also be extremely helpful.

**Comment by Drek282** [comment]
Ok, I see it's cstrikes.  That game hasn't been tested, so attaching logs would be extremely helpful.

**Comment by Drek282** [comment]
If you don't want to post your logs here, here's a friend link on Steam.  You can chat with me there and we can figure out some other way for you to send me some logs.  Just so we're clear, all I will do with your logs is use them to improve PS.  The stats they produce will not be published to a public site and they will in no way shape or form be mined for data.

https://s.team/p/jjddw/HBGBJJNW

I will leave this invite up for a day or two, then delete it, or delete it when you use it, whichever comes first.

**Comment by janzagata** [comment]
If Bot ignore is set to true, I would expect, that after processing of this log file, player Mr. Pink would have 0 kills and 0 headshots (I was playing against bots).

I can say, bug is in cstrikes module, but I didnt find way how the kills are ignored, so I did not wanted to tweak the headshots. 

[l0715012.log](https://github.com/Drek282/PsychoStats/files/6826179/l0715012.log)

**Comment by Rosenstein** [comment]
Have you ran stats.pl before setting ` Ignore BOT's?` to yes?
And do you perhaps use some plugin that duplicates your logs?

**Comment by Drek282** [comment]
The issue was present in the logs that I downloaded from the server.  I don't think those logs have been renamed, unless a plugin has done so.  I'm going to take a closer look at the logs, I think the theory that janzagata and myself came to was that a plugin was reporting headshots twice.  However, if that was the case the headshot percentages should also be screwed up if bots are not ignored, and they don't seem to be.

There are two places in the code where bot detection happens, and my guess is that one of them is working properly while the other is not.  So this may be a real PS issue, and not an issue with a plugin.  I am going to take a look at the code and see  if I can figure out what is going on.

**Comment by Drek282** [comment]
Bot detection is working properly.  I think we're back to the stats plugin not reporting weaponstats properly.  The only thing I can suggest is what I already suggested and that is that you make sure you are running the latest version of the stats plugin.  The other possibility is that you don't need a stats plugin for CSS at all, mp_logdetail 3 might be what you need in your server.cfg.  But I'm not 100% certain on that.

**Comment by Drek282** [comment]
Looking at my server cfg for the HL2/Source mod I run, I have mp_logdetail 3 in my server.cfg and I don't get hit locations, so it might be that you do need a plugin, so again, I would suggest that you make sure you are running the most up to date version of the plugin.

**Comment by Drek282** [comment]
I've been looking at the SuperLogs plugin for CS:S.  I would suggest the following settings:

superlogs_locations 0
superlogs_ktraj 0
superlogs_headshots 0
superlogs_wstats 1
superlogs_actions 0

Player positions are the first two, and I think those are already logged by default.  The headshots is an extra headshot logging, and I think that is what is screwing things up.  Headshots are included in the wstats setting and shouldn't also be included in the headshots stat.  I have no idea what the actions are, but my guess is they aren't helpful to PS...

**Comment by Drek282** [comment]
If you find that killer and victim positions aren't being logged, then probably the following is what you need:

superlogs_ktraj 1

**Comment by janzagata** [comment]
At the end of the day, problem was with SuperLog Plugin that did not distinguish in between (fake)clients.

**Comment by Drek282** [comment]
Thanks for letting us know.
