### ISSUE TITLE
steam_community_url is broken

### ISSUE THREAD

**Issue by Drek282** [Drek282/PsychoStats#59]

**Comment by Rosenstein** [comment]
Somewhat broken:

Guest sees:
![image](https://user-images.githubusercontent.com/4959837/126565007-54fc6797-febb-4cd4-9297-fc487ddcfd46.png)

Logged in root user sees
![image](https://user-images.githubusercontent.com/4959837/126565034-af1a7ce0-a1b7-4487-b559-8a6ae8da5069.png)

**Comment by Drek282** [comment]
I can't get Steam Profile Page to show on my stats under any circumstances.

**Comment by Drek282** [comment]
You need to install the bcmath php module for this to work.  Once you install that it works perfectly.
