### ISSUE TITLE
Psychostats update issue

### ISSUE THREAD

**Issue by dave102654** [Drek282/PsychoStats#75]
Hey,

     I am having some troubles with my Psychostats installs updating stats. If this isn't the place for this just delete,

and please tell me where to ask for help.

I have 4 game servers, 2 regular DoD and 2 DoDS on 2 different server hosts. Have web sites on 2 different web hosts. 

     Ps install is easy, and have been doing this for about 20yrs off and on. 

     I have 4 ps sites on one host, and a couple on a new one I am trying. When I set up a log source I get Successfully 

connected to the FTP server and verified the path exists but only If I move the files to my website. This is on all installs. 

When I exicute the stats.pl via cron with email I get a long text page, I assume it means the cron exicuted the .pl. However 

I get no stats at all. No error file in my ps installs. On one web host, with remote mysql I can update the stats from my 

desktop with cd c:\pathto.pl on my c drive. They update fine like that. The other doesn't allow remote so I have to use cron 

or console with email output being the txt file, no stats. 

     Have 3.2.7b, 3.2.8b, PHP is 7.3 on one and 7.4 on the other.

     The installs not being able to see log files on game server is probably port blocking some way, I am not getting much help

with this from support.

     Best part is, I installed Wamp64 on an old desktop. Did 4 ps installs. Got stats updating from the game servers by 

clicking on the stats.pl. Might see if I can get a static ip, point one of my domains and run from home. Window task manager

sucks tho.

     If you need any more info just ask. Any ideas what I'm up against? Or any reasonably priced host that I can run psychostats 

on. Need to get this resolved.

Many thanks,
Dave

**Comment by Drek282** [comment]
I'm really sorry, but I'm not working on this much anymore.  Remote log processing is something that I didn't test, and I'm in the middle of a project so I can't really look at it for you right now.

**Comment by dave102654** [comment]
Ok thanks for the reply, if you should think of anything or any place I might get help please let me know. Good luck on your projects.
Dave

**Comment by Drek282** [comment]
The only things I can think of off the top of my head are either you have max days set incorrectly, as in you are trying to parse old logs and you need to set the max days to something that will handle logs that are old, or the method used to handle the ftp is obsolete, or needs to be updated in some way.  The other possibility is a firewall issue.

**Comment by Rosenstein** [comment]
I'm little late to this party, but did you get this resolved @dave102654 ?

**Comment by dave102654** [comment]
Yes it is fixed. I was having to upload the logs to my server host to update them. That host was blocking the ports needed for psychostats to reach the game server logs. It is one problem or another with the different host that I have tried. I finally found one that everything works on and all is good. 

Thanks for checking on it,
Dave

**Comment by Drek282** [comment]
I guess we'll call this closed...
