### ISSUE TITLE
HS% over 100%

### ISSUE THREAD

**Issue by bobl61** [Drek282/PsychoStats#83]
How can the headshot percentage be over 100%?

![2023-06-03_111807](https://github.com/Drek282/PsychoStats/assets/107001969/7d912553-ca6f-467f-ae6e-81412b6d3fb4)

![2023-06-03_111340](https://github.com/Drek282/PsychoStats/assets/107001969/e7418ba3-0094-4c8d-80ac-62fdff1b2ba6)

**Comment by Drek282** [comment]
A headshot that didn't result in a kill.  That's a flaw in the way headshot percentage is calculated.  ST clearly assumed that every headshot would result in a kill, but that apparently isn't true.

**Comment by bobl61** [comment]
> A headshot that didn't result in a kill. That's a flaw in the way headshot percentage is calculated. ST clearly assumed that every headshot would result in a kill, but that apparently isn't true.

ST?

**Comment by Drek282** [comment]
Yes, Stormtrooper, the original developer of PsychoStats.

**Comment by Drek282** [comment]
I have no plans to fix this at this time.  This is an original design issue and not something I'm interested in putting any effort into.
