### ISSUE TITLE
All players are ranked #1

### ISSUE THREAD

**Issue by bobl61** [Drek282/PsychoStats#85]
Yeah...it's me again. Okay, so I completely deleted ALL the PS files. I reinstalled PS with the latest files (I see the cookie issue has been addressed for non https sites). I parsed the logs last night. I saw that all the players were ranked #1. The stats ran again this morning at 9 AM. All the players  are still ranked #1. 

![2023-06-13_101840](https://github.com/Drek282/PsychoStats/assets/107001969/a6a0ce27-06f3-451e-8d53-fb3d1725ef16)

![2023-06-13_101936](https://github.com/Drek282/PsychoStats/assets/107001969/baa14fd7-dfa2-4cac-a217-d6577d72c5a9)

**Comment by bobl61** [comment]
> That's a weird one. Going to run some tests, I'll get back to you shortly.

Okay, thanks.

**Comment by Drek282** [comment]
Ok, I reinstalled PS from scratch, with the cstrikes module, ran stats.pl on the logs you sent me, through sftp.  This is what I got.
![demo](https://github.com/Drek282/PsychoStats/assets/37514294/c8422868-6cf6-4063-883e-5647ee45955b)

**Comment by Drek282** [comment]
Ok, I think I may know what's going on.  You need to delete all the stats, then run stats.pl again.  If that doesn't work, you need to reinstall PS from scratch and drop and recreate the database.  Something is wrong with your database.  That "Optimizing database tables ..." entry in your logs is an error that indicates you are trying to run stats.pl when you've manually deleted data from your database, not using the Admin CP functionality.

**Comment by bobl61** [comment]
It must have been a database issue. When I first did the reinstall, I didn't drop the database, I just dropped all the tables. I tried deleting all the stats via Admin, running stats.pl again, but got the same result. I dropped the database, created a new one, reinstalled, ran the stats again, and it looks okay now.

**Comment by bobl61** [comment]
The Google map is now working. Great job!

![2023-06-13_132539](https://github.com/Drek282/PsychoStats/assets/107001969/538887e1-6dc4-4612-b73c-30beb7f9f1ec)

**Comment by Drek282** [comment]
Hey, *you* got that working!  Congratulate yourself!  I found getting that Google Maps API key a little confusing and frightening...

**Comment by Drek282** [comment]
Going to keep this open at least until I get a chance to look at the database options during the install.

**Comment by Drek282** [comment]
Closing.
