### ISSUE TITLE
Warning: Undefined array key "steam_community_url"

### ISSUE THREAD

**Issue by bobl61** [Drek282/PsychoStats#87]
Getting the same warning message on every player profile. I tried emptying the temp directory (except for .htaccess and index.html).
`Warning: Undefined array key "steam_community_url" in C:\xampp\htdocs\psycho.servegame.com\temp\default-en_US-^%%8C^8C2^8C205E49%%player_profile.html.php on line 15`

![2023-06-28_132835](https://github.com/Drek282/PsychoStats/assets/107001969/3893049e-3dd5-4464-a3a6-543a632d8a9a)

![2023-06-28_132856](https://github.com/Drek282/PsychoStats/assets/107001969/8f5bee60-9932-4678-bf93-64c7eb002972)

**Comment by Drek282** [comment]
I just fixed that error.  The only file you need to update is player.php.

**Comment by bobl61** [comment]
> I just fixed that error. The only file you need to update is player.php.

What took you so long? : -)
