### ISSUE TITLE
Player History

### ISSUE THREAD

**Issue by bobl61** [Drek282/PsychoStats#89]
When clicking on any players name, then view history, getting warning messages:
`Warning: Undefined variable $limit in C:\xampp\htdocs\psycho.servegame.com\plrhist.php on line 38

Warning: Undefined variable $id in C:\xampp\htdocs\psycho.servegame.com\includes\PS\PS.php on line 690

Warning: Undefined array key "steam_community_url" in C:\xampp\htdocs\psycho.servegame.com\temp\default-en_US-^%%CD^CD0^CD052E8D%%player_profile.html.php on line 15`

![2023-07-03_134652](https://github.com/Drek282/PsychoStats/assets/107001969/a3b369e4-87d2-40b1-8b9f-6feb3ec9c9ff)

Saw this in error log:
`[Mon Jul 03 13:48:51.140789 2023] [php:warn] [pid 5348:tid 1884] [client 185.187.243.244:48040] PHP Warning:  Undefined variable $limit in C:\\xampp\\htdocs\\psycho.servegame.com\\plrhist.php on line 38, referer: https://psycho.servegame.com/player.php?id=268
[Mon Jul 03 13:48:51.144647 2023] [php:warn] [pid 5348:tid 1884] [client 185.187.243.244:48040] PHP Warning:  Undefined variable $id in C:\\xampp\\htdocs\\psycho.servegame.com\\includes\\PS\\PS.php on line 690, referer: https://psycho.servegame.com/player.php?id=268
[Mon Jul 03 13:48:51.149686 2023] [php:warn] [pid 5348:tid 1884] [client 185.187.243.244:48040] PHP Warning:  Trying to access array offset on value of type bool in C:\\xampp\\htdocs\\psycho.servegame.com\\temp\\default-en_US-^%%A2^A29^A29BC927%%player_left_column_mod.html.php on line 5, referer: https://psycho.servegame.com/player.php?id=268
[Mon Jul 03 13:48:51.167704 2023] [php:warn] [pid 5348:tid 1884] [client 185.187.243.244:48040] PHP Warning:  Undefined array key "steam_community_url" in C:\\xampp\\htdocs\\psycho.servegame.com\\temp\\default-en_US-^%%CD^CD0^CD052E8D%%player_profile.html.php on line 15, referer: https://psycho.servegame.com/player.php?id=268
[Mon Jul 03 13:48:51.168704 2023] [php:warn] [pid 5348:tid 1884] [client 185.187.243.244:48040] PHP Warning:  Trying to access array offset on value of type bool in C:\\xampp\\htdocs\\psycho.servegame.com\\temp\\default-en_US-^%%4D^4D2^4D2F243E%%plrhist.html.php on line 69, referer: https://psycho.servegame.com/player.php?id=268
[Mon Jul 03 13:48:51.576550 2023] [php:warn] [pid 5348:tid 1884] [client 185.187.243.244:48040] PHP Warning:  Undefined variable $sum in C:\\xampp\\htdocs\\psycho.servegame.com\\player.php on line 428, referer: https://psycho.servegame.com/plrhist.php?id=268
[Mon Jul 03 13:48:51.578608 2023] [php:warn] [pid 5348:tid 1884] [client 185.187.243.244:48040] PHP Warning:  Undefined array key "key_size" in C:\\xampp\\htdocs\\psycho.servegame.com\\player.php on line 462, referer: https://psycho.servegame.com/plrhist.php?id=268
[Mon Jul 03 13:48:51.578608 2023] [php:warn] [pid 5348:tid 1884] [client 185.187.243.244:48040] PHP Warning:  Undefined array key "key_size" in C:\\xampp\\htdocs\\psycho.servegame.com\\player.php on line 468, referer: https://psycho.servegame.com/plrhist.php?id=268`

**Comment by Drek282** [comment]
I've fixed that error.  Unfortunately you are going to have to download the latest version from the repo, delete all your files except for the config.php and stats.cfg files, replace all the files, and do a full reinstall including dropping and recreating the database.  GDPR compliance has changed a lot of files, and the database structure as well.

**Comment by bobl61** [comment]
I'll wait until the Gungame mod is finished,

**Comment by Drek282** [comment]
That is going to be a few days, I'm doing an OS reinstall.

**Comment by bobl61** [comment]
Again? 
![3748869](https://github.com/Drek282/PsychoStats/assets/107001969/af3d81ec-c53e-4f69-8071-97c01b40845e)

**Comment by Rosenstein** [comment]
You could import .sql files from 'migrations' folder and get new features without destroying DB

**Comment by Drek282** [comment]
It's a long story.  I upgraded to Debian 12 in place.  It was a disaster.  I thought Debian 12 was a disaster.  So I install Debian 11 again, but in that process and the recovery, I discovered that my backups weren't working as I thought they were, and in fact I really didn't understand how they were working at all, so I figured them out.

Then I did some more reading up on Debian 12, and figured out that it wasn't as bad as I thought it was, and I was going to want to upgrade to it some day anyway, progress and all that, so that's what I'm doing.  But Debian 12 is a big change from Debian 11, and I had to do a clean install, and reconfigure everything.  But I'm getting there.  As you can see, I'm here...
