### ISSUE TITLE
Hasn't Properly Been Installed

### ISSUE THREAD

**Issue by Vonaducci** [Drek282/PsychoStats#91]
I'm trying to install psychostats for dod 1.3 and I manage to go through the installer flawlessly, but when I'm prompted to visit the admin control panel for the first time, the page says: PsychoStats hasn't been properly installed, please see INSTALL.md for details. I followed everything from install.md to a tee, so I have no clue whats wrong.

I properly installed psychostats, so what happened? I have SSL on the website, so it's not that. I legitimately have no clue how to fix this.

Im using windows and XAMMP.

**Comment by Drek282** [comment]
Windows and XAMMP aren't intended to be used in a production environment.  My guess is it *is* that https isn't set up properly.  Having said that, are you using the latest PS available from this repo, with the latest version of the DOD module?  The latest version of PS is not the version available as a package.  You need to click on the green "Code" button and choose "download as Zip" for that.  I should probably remove that, it is broken and won't work with PHP 8.

**Comment by Vonaducci** [comment]
Yes, I am using the latest PS available from this repo, I clicked code, and then download as ZIP. If this: https://github.com/Drek282/ps_dod is the latest version of the DOD module, I am using the latest version of that too. I found one thing curious though about that module, the list of weapons is actually the list of weapons from DoD:S and includes none of the weapons from 1.3. For example, there are pictures for the rifle grenades which 1.3 didn't have and there are no pictures for the fg42, bren, or any british gun for that matter.

I can access my website with zero issues from https://mywebsite.com, so that's pretty indicative that I've set up HTTPS properly right? I've never had a single issue with HTTPS not being enabled and I've installed mybb, sourcebans, hlstatsx, and amxbans, all without issue. I saw someone had an issue caused by https not being enabled, and I changed cookiessecure => to 0, but that didn't work either.

**Comment by Vonaducci** [comment]
> Proper way: Step 1 - Download main PS package https://github.com/Drek282/PsychoStats/archive/refs/heads/main.zip Step 2 - Download DoD PS addon package https://github.com/Drek282/ps_dod/archive/refs/heads/main.zip Step 3 - Extract everything in same folder Step 4 - Go through the installation process again.

I just downloaded those files hoping they differed from the ones I downloaded, but after having installed them both, same issue:

PsychoStats hasn't been properly installed, please see INSTALL.md for details.

I will go over my install process to ensure I haven't done anything wrong:

1.) Login to PHPmyadmin, create a database called "psychostats"
2.) Copy every file in www from psychostats-main.zip to C:\XAMMP\htdocs\psychostats
3.) Copy every file in www from ps_dod-main.zip to C:\XAMMP\htdocs\psychostats
4.) Edit config.php which came from ps_dod-main.zip so it reads:
<?php
$dbtype = 'mysql';
$dbhost = 'localhost';
$dbport = '';
$dbname = 'psychostats';
$dbuser = 'HereIsWhereMyDBUsernameWouldBe';
$dbpass = 'AndHereIsWhereMyPasswordWouldBe';
$dbtblprefix = 'ps_';
$site_url = '';
?>
5.) Visit https://mydomain.com/psychostats/install/index.php to begin the install process. The page successfully loads!
6.) Step through the installer and I have no issues, not a single error.
7.) Read that psychostats has successfully been installed! I click the button to visit my admin control panel for the first time.
8.) PsychoStats hasn't been properly installed, please see INSTALL.md for details. <- Who knows why it happens.

I have attached screenshots to show some important steps of the install processes to ensure I'm not doing anything wrong:
![sysmteanalyzed](https://github.com/Drek282/PsychoStats/assets/145424300/27caacc9-68b2-4e3d-a6d4-4e17d150bd2a)
![databasesetupconfirmed](https://github.com/Drek282/PsychoStats/assets/145424300/6bce890b-b3a4-456a-8996-d9b14da263a6)
![dbinitialized](https://github.com/Drek282/PsychoStats/assets/145424300/e08e5599-9411-44aa-a12b-1f3ea9347271)
![successinstall](https://github.com/Drek282/PsychoStats/assets/145424300/afbd6c5d-4cb0-4d50-9ba9-801950d12bcb)

**Comment by Vonaducci** [comment]
> Check if 'install' folder is deleted

That was the issue! Psychostats was deleting every file inside the "install" folder, but until the install folder itself is deleted, the page will display: PsychoStats hasn't been properly installed, please see INSTALL.md for details.

Now that I have deleted it, the website seems to work fine (at least within the 2 mins I have glanced at it). Hopefully I won't run into any issues installing it to my game server or running stats.pl. 

I'll update and let everyone know if I can't get the rest finished,

Thank you!

**Comment by Drek282** [comment]
That folder should delete automagically.  I've never *not* had that work.  I blame the aliens...

**Comment by Drek282** [comment]
My guess is it's a permissions issue and the user you are running Apache under didn't have the necessary permissions to delete that folder.

**Comment by Vonaducci** [comment]
> My guess is it's a permissions issue and the user you are running Apache under didn't have the necessary permissions to delete that folder.

Okay one last issue starting the stats.pl file from the command line in PowerShell:

```
PS C:\Windows\system32> cd C:\Users\Vonaducci\Server\psychostats\root
PS C:\Users\Vonaducci\Server\psychostats\root> perl stats.pl
[INFO] PsychoStats v3.2 initialized.
[FATAL] Called from main(278) >>>
No log sources defined! You must configure a log source (or use -log on command line)!
[INFO] PsychoStats v3.2 exiting (elapsed: 00:00:00, logs: 0, lines: 0)
PS C:\Users\Vonaducci\Server\psychostats\root> perl stats.pl -log C:/Users/Vonaducci/Server/psychostats/root/psychostatslog.txt
[INFO] PsychoStats v3.2 initialized.
[WARNING] Error opening logsource directory C:/Users/Vonaducci/Server/psychostats/root/psychostatslog.txt: Invalid argument
[INFO] Daily updates about to be performed: maxdays,decay,activity,players,clans,ranks,awards
[INFO] Daily 'maxdays' process running (Last updated: Wed Sep  3 05:57:40 2008)
Deleting stale stats older than 2023-10-29 ...
Recalculating compiled stats ...
This may take several minutes ...
[INFO] Daily process completed: 'maxdays' (Time elapsed: 00:00)
[INFO] Daily 'decay' process skipped, decay is disabled.
[INFO] Daily 'clans' process running (Last updated: Wed Sep  3 05:57:40 2008)
[INFO] Daily 'ranks' process running (Last updated: Wed Sep  3 05:57:40 2008)
[INFO] Daily process completed: 'ranks' (Time elapsed: 00:00)
[INFO] Daily 'awards' process running (Last updated: Wed Sep  3 05:57:41 2008)
[INFO] No historical stats available. Aborting award calculations.
[INFO] PsychoStats v3.2 exiting (elapsed: 00:00:00, logs: 0, lines: 0)
PS C:\Users\Vonaducci\Server\psychostats\root>
```
It seems I am not correctly defining the -log file, and I can't find how to configure it online. Maybe there's another issue, I'm not sure.

**Comment by Rosenstein** [comment]
You define log source in Admin Control Panel, it is easier that way, since there is test feature.

**Comment by Rosenstein** [comment]
Also, you set it to the folder where game logs are located

**Comment by Vonaducci** [comment]
> Also, you set it to the folder where game logs are located

I see where to edit the log source in the admin control panel, but when I test I get:

```
Testing Results
Log source path was not found or is not readable! - Please verify the path
```

I know for certain the file exists at that path, I'll show a screenshot. I made sure it's not "read only" and there's no permission or access issues as every other application access every file just fine.

I'm not actually sure where the game logs are located or what directory that refers too. I tried C:/Users/Vonaducci/Server/hldsdod/dod/logs/psychostats.log which is where logs of the gameserver goes, but that didn't work either. I also tried C:/Users/Vonaducci/Server/hldsdod/logs/psychostats.log and lastly C:/Users/Vonaducci/Server/hldsdod/dod/addons/amxmodx/logs/psychostats.log

I also swapped the / slash for \, but that doesn't work and seems wrong because the log directories all begin with / in the ACP. 

Here's some screenshots of what I'm doing:
![logsource1](https://github.com/Drek282/PsychoStats/assets/145424300/d807b6a3-4430-4dd3-b21f-e417803760be)
![logsource2](https://github.com/Drek282/PsychoStats/assets/145424300/96215bd8-7c53-47cb-8cd0-42df1ec60310)
![psychostats_log_directory](https://github.com/Drek282/PsychoStats/assets/145424300/266386f2-b1a6-4af7-abda-484d9f01963b)
![didntworkeither](https://github.com/Drek282/PsychoStats/assets/145424300/098f0407-b414-41d5-8cf4-8c44181419e9)

**Comment by Drek282** [comment]
You need to set that log source to the folder where the logs for your game server are located.  something like hlds\cstrike\logs

**Comment by Rosenstein** [comment]
Should be "C:/Users/Vonaducci/Server/hldsdod/logs/". You need file path that points to a folder that contains many log files named something like "L231130.log", so game server logs not plugin logs

**Comment by Vonaducci** [comment]
> You need to set that log source to the folder where the logs for your game server are located. something like hlds\dod\logs

Awesome, so my issue was I was refering to a specific file, "psychostats.log" when I should have just put C:/Users/Vonaducci/Server/hldsdod/dod/logs

Now that I have it working just a few more questions:

First question: Is psychostats supposed to actively run and monitor the server or do I just schedule stats.pl to run once a day with windows task scheduler, kind of like how awards.pl works in hlstatsx? I ask because when I ran it, it scanned my logs, added all the information to the database, and then closed (I'm assuming that's the intended functionality). 

I wasn't able to get the live server view to work either until I commented out line 208 of halflife.php
![liveserveradderror](https://github.com/Drek282/PsychoStats/assets/145424300/507aa15a-1a7c-4694-8543-75b829151c2c)

It works after I comment out line 208:
$this->data['appid']			= $this->_getbyte() | ($this->_getbyte() << 8);

, but it causes the live server view to look like:
![slightlyglitched](https://github.com/Drek282/PsychoStats/assets/145424300/48774653-5910-444e-b090-c4f6b70c23fa)

Is there anyway to fix that or is that how it's supposed to look?

**Comment by Drek282** [comment]
You need to run stats.pl on a schedule, and I will look at that error.  The DOD module hasn't been properly tested since I started updating PS however many years ago that was now.

**Comment by Vonaducci** [comment]
> You need to run stats.pl on a schedule, and I will look at that error. The DOD module hasn't been properly tested since I started updating PS however many years ago that was now.

Thanks! I appreciate all the help today. If ever you end up fixing that, I wouldn't mind to be notified. Thank you!

**Comment by Drek282** [comment]
Please email me at olstairs at rogers dot com and provide the ip address and port for your server.  I will want to look at that tomorrow am.

**Comment by Rosenstein** [comment]
Add me to cc, gadget_gadget1_at_yahoo_com

**Comment by Vonaducci** [comment]
I've got one other small error: 

I was having trouble with psychostats updating with new information, but I discovered that because I left the psychostats.log file in my log file directory, it would read nothing from that empty file and consequently update nothing on my website. I removed that file, cleared my stats, and re-added my log directory, and when I ran stats.pl it updated with new player information, but now there's no rewards.

I'm not sure why, but even after reinstalling, psychostats no longer calculates rewards. I have rewards set to daily too, so it's pretty confusing. Perhaps it is because when I first ran stats.pl it was 11/30/23 and now the website says its 12/1/23 so no awards are being calculated. I tried to go back before 12/1/23 and run stats.pl again, but when I set my timezone to -7 I started getting errors.

Might anyone know the reason why all of the sudden under awards it says:
```
No Awards Found

There are currently no awards in the database to display.

```
because it was working before.

**Comment by Rosenstein** [comment]
> I've got one other small error:
> 
> I was having trouble with psychostats updating with new information, but I discovered that because I left the psychostats.log file in my log file directory, it would read nothing from that empty file and consequently update nothing on my website. I removed that file, cleared my stats, and re-added my log directory, and when I ran stats.pl it updated with new player information, but now there's no awards.
> 
> I'm not sure why, but even after reinstalling, psychostats no longer calculates awards. I have awards set to daily too, so it's pretty confusing. Perhaps it is because when I first ran stats.pl it was 11/30/23 and now the website says its 12/1/23 so no awards are being calculated. I tried to go back before 12/1/23 and run stats.pl again, but when I set my timezone to -7 I started getting errors.
> 
> Might anyone know the reason why all of the sudden under awards it says:
> 
> ```
> No Awards Found
> 
> There are currently no awards in the database to display.
> ```
> 
> because it was working before.
> 
> EDIT: I forgot that I changed my settings so that daily awards are given too. Once I set it back to default, no daily awards, the awards came back.

Enable daily awards and report back in 24h, after stats.pl is run again 🙂
![image](https://github.com/Drek282/PsychoStats/assets/4959837/72b06767-d4f8-4a45-944b-a2dccfa2845c)

**Comment by Rosenstein** [comment]
Actually, you can run 'stats.pl -daily' and see if it updates.

P.S. Always run 'stats.pl -debug -debugfile' to see more output from the script and save it to file.
On Windows, -verbose switch is used by default.
