### ISSUE TITLE
Undefined array key "bots_listed"

### ISSUE THREAD

**Issue by bobl61** [Drek282/PsychoStats#97]
`Warning: Undefined array key "bots_listed" in C:\xampp\htdocs\psycho.servegame.com\includes\PS\PS.php on line 1200

Warning: Undefined array key "bots_listed" in C:\xampp\htdocs\psycho.servegame.com\includes\PS\PS.php on line 2756`

[https://psycho.servegame.com/](url)

**Comment by Drek282** [comment]
You need to update your database structure.

In the latest version of PS, in the "www\install\migrations" folder there is a file "327b_base_20240122_01_bot-ranking-switch.sql".

You can either import that file into your database, or you can open it, ctrl-a, ctrl-c and run that sql command on your database in the SQL section of PHPMyAdmin, or however you manage your database.

**Comment by Drek282** [comment]
If you are running the latest version of PS you should do the same with the files:

327b_base_20240122_00_credits.sql
327b_base_20240128_00_updating-themes.sql

**Comment by bobl61** [comment]
That took care of the warnings, but PS seems to be loading slower now.

**Comment by Drek282** [comment]
The main player page will be slower, there are additional queries now.  Those were added as part of the security update.

**Comment by Drek282** [comment]
That is a genuine concern.  I'm going to think on it for a bit.  I don't think it's a game breaker, it's just a bit of a hesitation.  What do you think?

**Comment by bobl61** [comment]
Well, dang 'Page loaded in 2.89735 seconds with 1237 SQL queries'. I guess less than 3 seconds for that many queries is reasonable. Yeah...not a game breaker, I was just used to it loading in under a second :-)

**Comment by Drek282** [comment]
Going to run some tests.  The code that checks to see if the sort queries are valid may be overkill.  It does prevent errors, but those errors only occur if someone is deliberately attempting to hack the software, and they aren't harmful, as long as the input is sanitized, which it is.

**Comment by Drek282** [comment]
That change only adds one query and makes very little difference in load times.  I'm going to keep poking at it and see if something else is the cause.

**Comment by Drek282** [comment]
I kinda think it may simply be a matter of more players being listed.

**Comment by Drek282** [comment]
I'm going to open a new issue about the number of SQL queries on the main player listing page.

**Comment by Drek282** [comment]
@bobl61 this discussion is continuing [here](https://github.com/Drek282/PsychoStats/issues/98).

**Comment by Rosenstein** [comment]
@bobl61 
I'm happy to say that excessive queries on page load have been fixed in 1f4f8cfb57e007db822ddcec9afd1c57392f734e commit.
